# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_community <- function(abundance, interaction, K, d0, b, m, save_int) {
    invisible(.Call('_GillesCom_create_community', PACKAGE = 'GillesCom', abundance, interaction, K, d0, b, m, save_int))
}

load_community <- function(abundance, trajectories, interaction, K, d0, b, m, time, save_int) {
    invisible(.Call('_GillesCom_load_community', PACKAGE = 'GillesCom', abundance, trajectories, interaction, K, d0, b, m, time, save_int))
}

abundance <- function() {
    .Call('_GillesCom_abundance', PACKAGE = 'GillesCom')
}

K <- function() {
    .Call('_GillesCom_K', PACKAGE = 'GillesCom')
}

d0 <- function() {
    .Call('_GillesCom_d0', PACKAGE = 'GillesCom')
}

birth <- function() {
    .Call('_GillesCom_birth', PACKAGE = 'GillesCom')
}

migration <- function() {
    .Call('_GillesCom_migration', PACKAGE = 'GillesCom')
}

elapsed_time <- function() {
    .Call('_GillesCom_elapsed_time', PACKAGE = 'GillesCom')
}

save_int <- function() {
    .Call('_GillesCom_save_int', PACKAGE = 'GillesCom')
}

get_interaction <- function() {
    .Call('_GillesCom_get_interaction', PACKAGE = 'GillesCom')
}

trajectories <- function() {
    .Call('_GillesCom_trajectories', PACKAGE = 'GillesCom')
}

Cbdm <- function(count = 1L) {
    invisible(.Call('_GillesCom_Cbdm', PACKAGE = 'GillesCom', count))
}

