# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_community <- function(abundance, interaction, K, d0, b, m, save_int, stochastic) {
    invisible(.Call('GillesCom_create_community', PACKAGE = 'GillesCom', abundance, interaction, K, d0, b, m, save_int, stochastic))
}

load_community <- function(abundance, trajectories, interaction, K, d0, b, m, time, save_int, cycles, stochastic) {
    invisible(.Call('GillesCom_load_community', PACKAGE = 'GillesCom', abundance, trajectories, interaction, K, d0, b, m, time, save_int, cycles, stochastic))
}

abundance <- function() {
    .Call('GillesCom_abundance', PACKAGE = 'GillesCom')
}

K <- function() {
    .Call('GillesCom_K', PACKAGE = 'GillesCom')
}

d0 <- function() {
    .Call('GillesCom_d0', PACKAGE = 'GillesCom')
}

birth <- function() {
    .Call('GillesCom_birth', PACKAGE = 'GillesCom')
}

migration <- function() {
    .Call('GillesCom_migration', PACKAGE = 'GillesCom')
}

elapsed_time <- function() {
    .Call('GillesCom_elapsed_time', PACKAGE = 'GillesCom')
}

elapsed_cycles <- function() {
    .Call('GillesCom_elapsed_cycles', PACKAGE = 'GillesCom')
}

save_int <- function() {
    .Call('GillesCom_save_int', PACKAGE = 'GillesCom')
}

get_interaction <- function() {
    .Call('GillesCom_get_interaction', PACKAGE = 'GillesCom')
}

trajectories <- function() {
    .Call('GillesCom_trajectories', PACKAGE = 'GillesCom')
}

Cbdm <- function(count = 1L) {
    invisible(.Call('GillesCom_Cbdm', PACKAGE = 'GillesCom', count))
}

Tbdm <- function(time) {
    invisible(.Call('GillesCom_Tbdm', PACKAGE = 'GillesCom', time))
}

