# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_community <- function(abundance, interaction, K, d0, b, m, save_int) {
    invisible(.Call('GillesCom_create_community', PACKAGE = 'GillesCom', abundance, interaction, K, d0, b, m, save_int))
}

abundance <- function() {
    .Call('GillesCom_abundance', PACKAGE = 'GillesCom')
}

K <- function() {
    .Call('GillesCom_K', PACKAGE = 'GillesCom')
}

d0 <- function() {
    .Call('GillesCom_d0', PACKAGE = 'GillesCom')
}

birth <- function() {
    .Call('GillesCom_birth', PACKAGE = 'GillesCom')
}

migration <- function() {
    .Call('GillesCom_migration', PACKAGE = 'GillesCom')
}

time <- function() {
    .Call('GillesCom_time', PACKAGE = 'GillesCom')
}

save_int <- function() {
    .Call('GillesCom_save_int', PACKAGE = 'GillesCom')
}

interaction <- function() {
    .Call('GillesCom_interaction', PACKAGE = 'GillesCom')
}

history <- function() {
    .Call('GillesCom_history', PACKAGE = 'GillesCom')
}

Cbdm <- function(count = 1L) {
    invisible(.Call('GillesCom_Cbdm', PACKAGE = 'GillesCom', count))
}

